{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongopulse.fullname" . }}
  labels:
    {{- include "mongopulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_DSN: {{ .Values.mongoDSN | quote }}
{{- end }}
