apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongopulse.fullname" . }}
  labels:
    {{- include "mongopulse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "mongopulse.selectorLabels" . | nindent 4 }}
